Repository Workiva/over_react_codemod, pull requests merged in 2019-08, with the labels that each got.

#30 CPLAT-6619 React 16 StyleMap Codemod
  lib/src/executables/react_16_upgrade.dart
  lib/src/react16_suggestors/constants.dart
  lib/src/react16_suggestors/react_style_maps_updater.dart
  pubspec.yaml
  test/react16_suggestors/react_style_maps_updater_test.dart
Labels: Merge Requirements Met, RM Ready

#32 CPLAT-6576 Verify Exit Code
  lib/src/constants.dart
  lib/src/executables/react_16_upgrade.dart
  lib/src/util/component_usage.dart
  test/executables/react_16_upgrade_test.dart
  test/executables/test_components/file_with_comment/pubspec.yaml
  test/executables/test_components/file_with_comment/react_render_with_comment.dart
  test/executables/test_components/file_with_no_comment/pubspec.yaml
  test/executables/test_components/file_with_no_comment/react_render_with_no_comment.dart
  test/executables/test_components/file_with_validated_comment/pubspec.yaml
  test/executables/test_components/file_with_validated_comment/react_render_with_validated_comment.dart
  test/util.dart
Labels: Merge Requirements Met, RM Ready

#33 Style Map Codemod (Adding Greg's Suggestions)
  lib/src/react16_suggestors/react16_utilities.dart
  lib/src/react16_suggestors/react_style_maps_updater.dart
  test/react16_suggestors/react_style_maps_updater_test.dart
Labels: Merge Requirements Unmet

#37 CPLAT-6814 Update copyUnconsumedDomProps usage
  lib/src/component2_suggestors/copyunconsumeddomprops_migrator.dart
  lib/src/executables/component2_upgrade.dart
  test/component2_suggestors/copyunconsumeddomprops_migrator_test.dart
Labels: Merge Requirements Unmet

#34 CPLAT-6811 Update setState to setStateWithUpdater
  lib/src/component2_suggestors/setstate_updater.dart
  lib/src/executables/component2_upgrade.dart
  test/component2_suggestors/setState_updater_test.dart
Labels: Merge Requirements Met, RM Ready

#36 CPLAT-6813 Check for componentWillUpdate and componentWillReceiveProps
  lib/src/component2_suggestors/component2_constants.dart
  lib/src/component2_suggestors/deprecated_lifecycle_suggestor.dart
  lib/src/executables/component2_upgrade.dart
  lib/src/util.dart
  pubspec.yaml
  test/component2_suggestors/deprecated_lifecycle_suggestor_test.dart
  test/util_test.dart
Labels: Merge Requirements Met

#41 CPLAT-7029 Fix style map codemod edge cases
  lib/src/react16_suggestors/react_style_maps_updater.dart
  test/react16_suggestors/react_style_maps_updater_test.dart
Labels: Merge Requirements Unmet, RM Ready
